docs/USER-STORIES.md
Keep the user stories generic, leave the TUF related comments to a
minimum. The idea is to describe what the repository can do, whether
it's implemented with TUF or not.
Signed-off-by: Jussi Kukkonen <jkukkonen@vmware.com>
---
Fixes #8
=> user stories: Remove TUF specific fluff

playground/README.md, playground/actions/compile/action.yml, playground/repo/README.md, playground/repo/playground/__init__.py, playground/repo/playground/_playground_repository.py, playground/repo/playground/publish.py, playground/repo/pyproject.toml
This action creates a metadata directory that is ready for client consumption:
* includes all versions of root
* uses versioned filenames for root, snapshot and targets and all delegated roles
=> Git-repo: Implement deploy action

playground/README.md, playground/repo/playground/_playground_repository.py, playground/repo/playground/status.py, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/sign.py
This allows adding/modifying target files in targets/, then running `playground-sign` to get those changes reflected in metadata.
Potential improvements:
* changed targets should be visible in signing event status report
* changed targets should be visible when signing changes by others
* running the tool multiple times looks strange because currently we just compare targets directory content to to current metadata (whther we have modified it or not). Possible fixes:
* when creating target changes, the comparison should be either to upstream signing event branch HEAD or just the latest commit in current branch
* just don't allow running the tool if there are uncommited changes
=> git-repo: Implement target changes

playground/actions/offline-version-bump/action.yml
Normally creating the signing event branch would trigger signing-event but inside the offline-version-bump action that does not happen automatically (to prevent trigger cycles).
Use createWorkflowDispatch() to trigger the signing-event workflow for each created branch.
Fixes #50.
=> actions: Dispatch signing event from offline-version-bump

playground/README.md, playground/actions/signing-event/action.yml
Two reasons:
* opening PRs via API requires non-default repository config
* maintainer may want to have more than threshold signatures as a policy, so automatically opening a PR is a bit premature
=> signing-event: Don't open PR, just offer a link

playground/README.md, playground/actions/online-version-bump/action.yml, playground/actions/snapshot/action.yml, playground/repo/playground/_playground_repository.py, playground/repo/playground/snapshot.py, playground/repo/pyproject.toml, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/delegate.py, playground/signer/pyproject.toml
* Optionally (and by default) use sigstore for online signing
* choosing sigstore for online signing means two keys are added (because there are two workflows that need the keys)
* GCP authentication is now done only if the auth details are set in GH repository variables -- this means the auth needs to be removed from playground-template
* requires securesystemslib main
=> Use sigstore signing keys

playground/README.md, playground/repo/playground/status.py, playground/signer/playground_sign/_common.py, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/delegate.py, playground/signer/playground_sign/sign.py
This is a work in progress to handle git fetch,commit & push within the tool.
It's not perfect but works when used appropriately
```
playground-sign EVENT-NAME
playground-delegate EVENT-NAME ROLE-NAME
```
It's a bit annoying that playground-sign now requires the event name but #64 is about removing that requirement
=> Signer git-integration (commit+push)

playground/repo/playground/_playground_repository.py, playground/repo/playground/bump_expiring.py, playground/repo/playground/snapshot.py, playground/repo/pyproject.toml, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/sign.py, playground/signer/pyproject.toml
95% of this PR is using new annotated tuf.repository accessors:
* `Repository.root()` and `Repository.edit_root()` (and similar for other metadata types)
* renamed online methods: `do_snapshot()` and `do_timestamp()`
Since mypy now exposes some new issues, There are also some annotation tweaks to fix those
=> Use new repository annotations and accessors

playground/signer/playground_sign/_common.py, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/delegate.py, playground/signer/playground_sign/sign.py, playground/tests/e2e.sh
This is mostly to test the securesystemslib implementation:
* Allow using sigstore identity as maintainer key
* Add UI to ask for email and issuer if using sigstore identity
* Fix tests (but note that sigstore maintainer keys are not actually tested -- I think that is not easy)
TODO:
* should not ask for email and identity: should instead do the the token acquisition and read the token... Could do this as POC even before sigstore-python provides this (which I think they should)
* should verify when signing that the identity is the one we expect
cc @lukpueh
=> Sigstore for maintainers

.github/workflows/ci.yml, .gitignore, playground/repo/playground/_playground_repository.py, playground/repo/test/test_playground_reposiory.py, playground/repo/test/test_repo1/root.json, playground/repo/test/test_repo1/targets.json, playground/repo/test/test_repo1/timestamp.json, playground/repo/test/test_repo2/root.json, playground/repo/test/test_repo2/timestamp.json
Any role can now configure `x-playground-signer-period` which is then used during bumping of metadata version to decide if the version should be bumped or not. If the `x-playground-signer-period` is not set, half the `x-playground-expiry-period` is used.
=> Configurable signer expiry

playground/README.md, playground/repo/playground/_playground_repository.py, playground/repo/playground/bump_expiring.py, playground/repo/playground/snapshot.py, playground/repo/playground/status.py, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/sign.py, playground/tests/e2e.sh, playground/tests/expected/target-file-changes/metadata/2.snapshot.json, playground/tests/expected/target-file-changes/metadata/3.targets.json
Redesign targets management once more:
* Users still make target content changes (outside of the tool)
* Let repository do the actual metadata changes during signing-event (the method is called status() but signing_event_update() might be better)
* Repository also documents the target changes at high level in the signing event
* Users sign normally: "playground-sign <EVENT>"
This makes the UX cleaner and does not complicate the repository too much.
The expected targets metadata change in e2e tests is because the PlaygroundRepository does not figure out version numbers as smartly as SignerRepository does, and ends up bumping versions more than needed: this could be fixed but it's not critical targets metadata.
This change means "playground-status" now makes commits and pushes them to …
=> Targets management version 4

playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/delegate.py, playground/signer/playground_sign/sign.py, playground/tests/e2e.sh
root is a special case since the signing keys are stored in root itself: 
we should be using both new and old keys in that case
The final PR ended up changing the signing and closing: 
* when roles are saved with `SignerRepository.close()` they are no longer signed even if keys are available
* those roles are added to the `unsigned` list
* after delegation changes (also after accepting an invite), all `unsigned` roles are explicitly signed
Comment below lists some advantages of this.
Fixes #103
Issues:
* There is no test yet: #106
* There is a related issue: if you run `playground-sign` to sign a change where your key has been removed from root, it probably won't notice you should sign: `_user_signature_needed()` should handle the special case of root (and check keys from the known good …
=> signer: During close, lookup correct root keys

playground/signer/playground_sign/_signer_repository.py, playground/tests/e2e.sh
Allow modifying online role config: This is an issue that would have been found by static type checks.
Fixes #100 
There is a related issue #101: the resulting published repository of the test does not change as it should because this change only touches root (and so snapshot process thinks no snapshot is needed, and then publish is not needed).
=> Fix online modify

playground/signer/playground_sign/_common.py, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/delegate.py, playground/signer/playground_sign/sign.py
The tool now mostly describes changes to roles metadata. There are still some gaps:
* This should be accompanied with strict validation (which allows us to not describe the things we validate)
* The key content changes are not yet handled
The code is pretty ugly... but I think it's partly unavoidable: even after better refactoring this is likely a long list of special cases. That said, there's definitely room for refactoring. I'd like to merge this and move on for now but I'll take opinions on this.
=> Improve playground-sign output

playground/repo/pyproject.toml, playground/signer/pyproject.toml
* sigstore-python 1.1.2 requires tuf ~= 2.1, this does not work because playground requires tuf 3
* Newer sigstore-python releases have not been made yet
* sigstore-python main branch does not work because the API has changed in multiple ways that securesystemslib does not support yet
This commit seems to be one of the few that could work:
* tuf dependency is loosened
* sign module API changes are not yet applied
=> dependencies: Try to find a working sigstore version/commit

.github/workflows/ci.yml, playground/repo/playground/_playground_repository.py, playground/repo/playground/bump_expiring.py, playground/repo/pyproject.toml, playground/signer/playground_sign/__init__.py, playground/signer/playground_sign/_common.py, playground/signer/playground_sign/_signer_repository.py, playground/signer/playground_sign/delegate.py, playground/signer/playground_sign/sign.py, playground/signer/pyproject.toml, playground/tox.ini
* added tox config
* Defined environments for linters and the tests we have now
* fixed a lot of things in signer/ to make linters happy: intention is to not have functional changes in the source code
* Enabled tox testing and linting on CI
* After the initial run (that installs dependencies)  tox is pretty snappy.
* repo is not linted yet
There is no documentation included, but 
```shell
pip install tox
tox -e lint-signer
tox -e test-e2e
tox -m test
tox -m lint
```
=> Enable linters and tests on CI

playground/repo/playground/_playground_repository.py, playground/repo/playground/status.py
* Fix the status output issue shown in #117
* Swap the output order of known good signatures and the signatures proposed in the signing event so that known good signature counts are shown first
=> Fix known good root signer status

playground/repo/playground/_playground_repository.py
This makes it possible for new signers to sign the existing metadata version.
Fixes #120
=> status: Don't require version bump if no payload change

playground/actions/online-version-bump/action.yml, playground/actions/snapshot/action.yml, playground/repo/playground/_playground_repository.py, playground/repo/playground/bump_expiring.py, playground/repo/playground/snapshot.py, playground/tests/e2e.sh
Closes #122 
The version bump and snapshot composite actions are now updated to accept two new parameters:
* `metadata_path`: the path inside the `publish` directory for the metadata, default is `/`, ie the root of the publish directory
* `targets_path`: the path inside the `publish` directory for the targets, default is `targets`. 
The parameters are provided to the `publish` method which makes sure to publish the metadata and targets accordingly, and then the final artifact is uploaded to pages.
=> Configurable deployment

playground/signer/playground_sign/_common.py, playground/signer/playground_sign/_signer_repository.py, playground/tests/e2e.sh, playground/tests/expected/root-key-rotation/metadata/1.root.json, playground/tests/expected/root-key-rotation/metadata/1.snapshot.json, playground/tests/expected/root-key-rotation/metadata/1.targets.json, playground/tests/expected/root-key-rotation/metadata/timestamp.json
Also print stdout when capturing git error as it's not always printed to stderr
Fixes: #130
=> A bit hackish fix for letting previous root signer sign current.

playground/actions/snapshot/action.yml, playground/repo/playground/snapshot.py, playground/tests/e2e.sh, playground/tests/expected/multi-user-signing/metadata/2.root.json, playground/tests/expected/root-key-rotation/metadata/2.root.json
Always publish a new repository version after a snapshot: previously we had an issue where signing events that only touched root metadata would not get published (because a snapshot would not get generated and then publish would not be done)
The real check pre-publish would be _"has any metadata changed since the last publish time"_ which may mean that we should use a branch to mark which commit we last published (something I've planned otherwise too). This PR is simpler however and starts publishing every time snapshot process runs: this currently means on every push to main
=> Snapshot publish fix
